language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jre
  
# command to install
install:
  - "pip install ."
  
# command to run tests
script: nosetests
