language: python
python:
  - "2.6"
  - "2.7"
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jre python-numpy
  - sudo pip install -U pip setuptools
  - pip install -r test-requirements.txt
install:
  - python setup.py install

# command to run tests
script: nosetests
