language: python
python:
- '2.6'
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq openjdk-7-jre python-numpy
- sudo pip install -U pip setuptools 
- pip install -r test-requirements.txt
install:
- python setup.py install
script: nosetests
deploy:
  provider: pypi
  user:
    secure: TeTyLrHulxk9MUrLFUccvAONM2Xc1e7+Tl1eNI+FSvxn9Gh/wIPSD7ZNH+n5tgs7BXt+53OIrIfU10nLMJP7cEZJVhwmdWNm0ONIhlRsH1+UJ8e1huPb3IFxdw5UJkiTjEfKulNp3p5q+EWaS7952MwWuehDds8bk0o6TVobvXI=
  password:
    secure: hHDQxBuoB6SGVIBiQNuCIc128VK1qwJm23PJNXzPmpzBEA5K6PTC6uwfC6ZZ4GpCoFvynD+VPyiJv+wGbBOJWd6sTvyCAiChzPNFaHho9rXaqWlhIL99qR2I4K5bv1m9jYFVGvT8HtgaVnXxsjCrm5dai+8ICTFqkZETqiSyqzo=
  distributions: "sdist"
  skip_cleanup: true # needed for jar
  on:
    tags: true
    # temporary workaround for travis issue #1675
    all_branches: true
    python: 2.7 # only deploy for this version
